### ISSUE TITLE
Ayi check

### ISSUE THREAD

**Issue by at15** [dyweb/Ayi#1]
Check if the environment (system or in vagrant) matches the need and generate a fix report. The report will be used by `Ayi fix`.

- [ ] Version control tools like Git
- [ ] Run-time environment like Node, PHP, Java.
- [ ] Package managers like NPM, Composer, Bower.
- [ ] CLI tools like Gulp, Doc-Viewer.
- [ ] Database like MySQL, MongoDB.
- [ ] and a lot more......

**Comment by arrowrowe** [comment]
Check if the environment (system or in vagrant) matches the need and generate a fix report. The report will be used by `Ayi fix`.

- [ ] Version control tools like Git
- [ ] Run-time environment like Node, PHP, Java.
- [ ] Package managers like NPM, Composer, Bower.
- [ ] CLI tools like Gulp, Doc-Viewer.
- [ ] Database like MySQL, MongoDB.
- [ ] and a lot more......

**Comment by kdplus** [comment]
It seems to be a big proj...
