### ISSUE TITLE
Ayi play

### ISSUE THREAD

**Issue by at15** [dyweb/Ayi#11]
Setup a temporary playground for js code, like a local jsfiddle, able to add local js files 

https://jsfiddle.net/  https://jsbin.com/?html,output

- [ ] support node js code
- [ ] support php code
- [ ] support regexp

**Comment by at15** [comment]
so many ayi in the air .... ayi ayi ayi 嘿金坷垃! 我要开始填坑了 .... @gaocegege 赌5毛我能在你开始写scrala之前开始写ayi

**Comment by gaocegege** [comment]
re @at15 听说你很跳

**Comment by at15** [comment]
re @gaocegege 填坑达人！

**Comment by at15** [comment]
an easier way is to add links to those sites in #15
