### ISSUE TITLE
Ayi Setup

### ISSUE THREAD

**Issue by arrowrowe** [dyweb/Ayi#2]
Find a convenient way to 
- [ ] install Ayi as a global command.
- [ ] update Ayi.

**Comment by at15** [comment]
install as global command is easy, just put ayi in /usr/local/bin and chmod it to executable, and update can use a self-update command that download and then replace the binary, just like composer, which is a phar. (means we can even use php to write this program)

**Comment by arrowrowe** [comment]
Agree. Just want someone to close this issue to begin the whole developing progress...

**Comment by at15** [comment]
@arrowrowe I will do it after I finish my c# project and setup go environment in ubuntu, You will see it began tonight (which is 10pm for you)
