### ISSUE TITLE
Migrate from godeps to glide

### ISSUE THREAD

**Issue by at15** [dyweb/Ayi#34]
since go1.6  already support vendor,  and 1.5 can support it via enable flag, we can use better package management. 

godeps lacks some feature that [glide](https://github.com/Masterminds/glide) has 

- specify package version
- simple command for install dependencies 

glide is more like `maven` and `npm`, while godeps might confuse a lot of developers come from other language.

The migrate process including

- [x] delete the godeps folder
- [x] use glide to manage dependencies
- [x] fix travis test
- [x] fix build
- [ ] fix warnings in Makefile @gaocegege current master got warning when run `make`, pls have a look at it if you get spare time, thx.
- [x] remove godeps builds, we no longer need this wrapper

**Comment by at15** [comment]
maybe we can use https://github.com/karalabe/xgo for cross build, it seems the default go installation can't cross compile @gaocegege

**Comment by gaocegege** [comment]
为什么不用dockerhub上golang的image进行交叉编译呢

**Comment by at15** [comment]
@gaocegege 这个就是用 docker 的

**Comment by gaocegege** [comment]
好吧。。。
