### ISSUE TITLE
Dont panic when .ayi.yml is not found

### ISSUE THREAD

**Issue by at15** [dyweb/Ayi#36]
A lot of Ayi commands does not require reading configuration from `.ayi.yml` besides, and the default behavior when type `Ayi` should simple show its usage regardless of config files existence.

**Comment by at15** [comment]
maybe generate a warning for config file not found is a better idea, and check the config value for each app, ie: mail, if required value is not found, print an error message, return an error code. Or is the painc the default error handling method in go? @gaocegege

**Comment by gaocegege** [comment]
这样逻辑会比较混乱吧~？

**Comment by at15** [comment]
感觉并不会额，那里检测只是检查yml文件是否存在，不存在配置文件也应该能继续工作，每个app加个checkConfig 然后调用一下，应该也不是很混乱
