### ISSUE TITLE
Can't run in vagrant in windows

### ISSUE THREAD

**Issue by at15** [dyweb/Ayi#5]
@arrowrowe  can't use it in windows vagrant box (ub14.04)

- zsh

It might be the `#!user/bin/env bash` or crlf causing trouble.

**Comment by arrowrowe** [comment]
I'll check that.

**Comment by at15** [comment]
@arrowrowe Also, please paste the detail error msg.

**Comment by at15** [comment]
The error is 'no such file or directory`, and file is `CRLF GBK`, after change to `LF UTF-8` everything works fine. Need to add a .gitattribute file avoid auto crlf and add .editorconfig for encoding

**Comment by at15** [comment]
@arrowrowe I think I have fixed it, you can just clone a new one if there are conflict when merge.

**Comment by arrowrowe** [comment]
Thanks. Checked.
