### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by at15** [dyweb/Ayi#6]
one is the google guide https://golang.org/doc/code.html
But many repos are not following this guide. I think we may have folder structure like following

````
lib 
   check.go
   install.go
   pkgmgr.go
   util
     cmd.go
config
   mysql
      exist.go/yml/json ?
      version
      install.go/bash  
   php
     ...
    pkg.go (composer)
  node 
    pkg.go (npm)
````

@arrowrowe @ComMouse @kdplus 

We can take https://github.com/convox/cli for example. (But go code is really not quite organized... just so many files in one folder) and https://github.com/GoogleCloudPlatform/kubernetes/tree/master/Godeps as well

**Comment by kdplus** [comment]
Get
